accelerate launch train_t2v_turbo_vc2.py \
    --output_dir=output/t2v-turbo-vc2 \
    --use_8bit_adam \
    --train_batch_size=1 \
    --n_frames 16 \
    --no_scale_pred_x0 \
    --reward_scale 1.0 \
    --video_rm_name vi_clip2 \
    --video_reward_scale 2.0 \
    --pretrained_model_path /path/to/VideoCrafter2_model.ckpt \
    --train_shards_path_or_url /path/to/webvid_data/train_data/{00000..99999}.tar \
    --video_rm_ckpt_dir /path/to/InternVideo2-stage2_1b-224p-f4.pt